# -*- coding: utf-8 -*-
"""irish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cCeydATqGtMGqAWoz_vj_xkVQZxOtxSd
"""

import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import tensorflow_datasets as tfds

dataset = pd.read_csv('sample_data/iris.csv')
dataset

X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

model = tf.keras.models.Sequential([
    keras.layers.Dense(4,input_shape=(4,),activation='tanh'),
    keras.layers.Dense(3,activation='softmax')
])

model.compile(optimizer=tf.compat.v1.train.AdamOptimizer(),loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

model.fit(X_train,y_train,epochs=150)

"""#0 = setosa 1 = versicolor 2 = virginica"""

X_test = np.array([[5, 3.9, 2, 0.5],[5,2.5,3,1],[8,3.5,6,2]])
y_pred = model.predict(X_test)
print(np.argmax(y_pred,axis=1))